/**
 * Texture for the fake terminals in the film. Each session is a list of lines;
 * the film reveals them one at a time as the window ages, so the agents are
 * still working when the purge arrives — none of them ever sit finished.
 *
 * Lines are capped at 34 characters. Longer ones clip against the window.
 */

export interface Session {
  readonly cmd: string;
  readonly lines: readonly string[];
}

/**
 * The one the reader types. It starts as a bare prompt; the command arrives a
 * character at a time on scroll, then launches an agent like any other.
 */
export const HERO_SESSION: Session = {
  cmd: 'my-agent "refactor auth"',
  lines: [
    'reading src/auth/session.ts',
    'reading src/auth/token.ts',
    'grep verifyToken across repo',
    '42 call sites, 9 files',
    'legacy jwt path still used',
    'checking auth/middleware.ts',
    'found duplicate refresh logic',
    'plan: unify into authService',
    'extracting verifyToken helper',
    'patched session.ts',
    'patched token.ts',
    'patched middleware.ts',
    'updating 9 call sites',
    'wait, oauth.ts imports old path',
    'fixing broken import',
    'patched oauth.ts',
    'running test suite',
    '3 tests failing, checking',
    'fixed stale mock in auth.test.ts',
    'tests pass 47/47, done',
  ],
};

export const SESSIONS: readonly Session[] = [
  {
    cmd: 'my-agent "why is login slow"',
    lines: [
      'reading routes/login.ts',
      'checking auth middleware chain',
      'adding timing marks',
      'running login flow locally',
      'bcrypt compare: 380ms',
      "that's the bottleneck",
      'cost factor set to 14',
      'way too high for sync path',
      'checking git blame on this line',
      'changed 8 months ago, no ticket',
      'testing cost factor 10',
      'bcrypt compare: 40ms',
      'still slow, checking db query',
      'missing index on users.email',
      'explains the seq scan',
      'adding index migration',
      'login now averages 55ms',
      '7x faster, down from 410ms',
    ],
  },
  {
    cmd: 'my-agent "write tests"',
    lines: [
      'scanning for existing tests',
      'found 0 tests in src/payments',
      'reading payments/invoice.ts',
      'mapping public functions',
      '6 functions, 2 edge cases each',
      'writing calculateTotal tests',
      'writing applyDiscount tests',
      'edge case: discount over 100%',
      "code doesn't clamp this",
      'adding clamp + regression test',
      'writing refund flow tests',
      'mocking stripe client',
      'running vitest',
      '4 passed, 2 failed',
      'failure: rounding mismatch',
      'switch to toBeCloseTo',
      'running vitest again',
      '18/18 passed, 92% coverage',
    ],
  },
  {
    cmd: 'my-agent "upgrade deps"',
    lines: [
      'scanning package.json',
      '47 deps, 12 outdated',
      'checking changelogs',
      'react 18.2 -> 18.3 minor',
      'next 14.1 -> 15.0 major',
      'running next codemods',
      'npm install',
      'peer dep conflict found',
      'eslint-config-next wants 14',
      'bumping eslint-config to ^15',
      'retrying install',
      'installed in 14.2s',
      'running test suite',
      '212 passed, 3 failed',
      'next/image prop errors',
      'patched 3 image callsites',
      '215 passed, 0 failed',
      '12 upgraded, 0 breaking',
    ],
  },
  {
    cmd: 'my-agent "fix flaky spec"',
    lines: [
      'reading test logs',
      'checkout_spec fails 1/20 runs',
      'reproducing locally',
      'looping test x50',
      'failed 6/50',
      'grepping async code paths',
      'cart.update() not awaited',
      'race: assertion runs first',
      'found in cart_service.ts:88',
      'adding await cart.update()',
      'rerun x50',
      'failed 1/50, still flaky',
      'digging deeper',
      'timer debounce, 300ms',
      'mocking timers in spec',
      'rerun x100',
      '100/100 passed',
      'diff: +4 -1, spec stable',
    ],
  },
  {
    cmd: 'my-agent "audit sql"',
    lines: [
      'scanning models/*.rb',
      'mapping active record calls',
      'found n+1 in orders#index',
      '40 queries per request',
      'adding includes(:line_items)',
      'down to 3 queries',
      'checking migrations/',
      'no index on orders.user_id',
      'explain analyze: seq scan',
      '1.2s scan on 400k rows',
      'writing migration',
      'add_index :orders, :user_id',
      'running migration',
      'query now 40ms',
      'checking for sql injection',
      'found raw string interp',
      'reports_controller.rb:52',
      'parameterized, 0 issues left',
    ],
  },
  {
    cmd: 'my-agent "port to esm"',
    lines: [
      'scanning src for commonjs',
      'found 142 require() calls',
      'found 89 module.exports',
      'mapping import graph',
      'rewriting src/index.js',
      'rewriting src/utils.js',
      'rewriting src/db/pool.js',
      'rewriting 34 more files',
      'snag: require.cache used',
      'cache.js has no esm equiv',
      'swapping to dynamic import',
      'package.json: type module',
      '12 files missing .js ext',
      'fixing extensions',
      'running test suite',
      '3 failing, jest esm config',
      'patched jest, rerun green',
      'done 231 files ✓ 0 fail',
    ],
  },
  {
    cmd: 'my-agent "read the rfc"',
    lines: [
      'opening rfc-9110.txt',
      '411 lines, http semantics',
      'skimming section headers',
      'sec 3: message routing',
      'sec 5: field values',
      'note: obsoletes rfc 7230',
      'cross-checking sec 8.3',
      'status codes table parsed',
      'found caveat on 101 switch',
      're-reading connection mgmt',
      'sec 9: conneg rules',
      'flagging must vs should',
      'checking errata db',
      'errata 6265 applies here',
      'drafting summary notes',
      'mapping reqs to our api',
      '4 open questions noted',
      'summary written 6 findings',
    ],
  },
  {
    cmd: 'my-agent "profile build"',
    lines: [
      'running build --profile',
      'cold build: 42.8s',
      'warm build: 8.1s',
      'tracing webpack compilation',
      'babel-loader: 11.2s',
      'ts-loader: 9.6s',
      'terser: 14.3s, largest',
      'spike: terser runs twice',
      'checking for dup plugin',
      'found dup in prod config',
      'removing duplicate terser',
      'rerunning cold build',
      'cold build: 29.1s',
      'warm build: 6.4s',
      'diffing bundle size',
      'bundle: 1.8mb → 1.6mb',
      'flamegraph: profile.json',
      '32% faster, -200kb bundle',
    ],
  },
  {
    cmd: 'my-agent "draft migration"',
    lines: [
      'reading schema.sql',
      'users table has 14 cols',
      'no soft-delete column yet',
      'adding deleted_at timestamptz',
      'checking existing migrations',
      'found 032_add_index.sql',
      'next id is 033',
      'drafting 033_soft_delete.sql',
      'add column, nullable, no default',
      'backfill: skip, all null is ok',
      'wait, orders references users.id',
      'cascade delete not affected',
      'writing down() for rollback',
      'down: drop column deleted_at',
      'checking reversibility',
      'reversible: yes',
      'running migrate --dry-run',
      'done → 033 ready, reversible',
    ],
  },
  {
    cmd: 'my-agent "grep for todos"',
    lines: [
      'grepping TODO across repo',
      'rg "TODO|FIXME" -n',
      '214 matches, 47 files',
      'clustering by theme',
      'auth: 12 todos, mostly stale',
      'payments: 31 todos',
      'src/billing/invoice.py:88',
      '"fix rounding before launch"',
      'that launch was 2019',
      'still unresolved, flag it',
      'api/routes.py has 19 todos',
      'same author, same week',
      'looks like a refactor stub',
      'tests/ dir: only 3 todos',
      'good test hygiene overall',
      'grouping into 5 clusters',
      'billing cluster is largest',
      'summary: 214 todos, 5 groups',
    ],
  },
  {
    cmd: 'my-agent "review pr 212"',
    lines: [
      'fetching pr 212 diff',
      '6 files changed, +312 -48',
      'touches auth middleware',
      'reading session.py changes',
      'new token refresh logic',
      'refresh skips expiry check',
      "that's a bug, not a nit",
      'checking test coverage',
      'no test for expired token',
      'also: silent except: pass',
      'swallows jwt.DecodeError',
      'should log or re-raise',
      'rest of diff looks clean',
      'naming consistent w/ repo',
      'commit history is tidy',
      'leaving 2 comments',
      'request changes: fix expiry',
      'verdict: not mergeable yet',
    ],
  },
  {
    cmd: 'my-agent "refactor auth"',
    lines: [
      'reading src/auth/session.ts',
      'grep verifyToken across repo',
      '42 call sites, 9 files',
      'legacy jwt path still used',
      'found duplicate refresh logic',
      'plan: unify into authService',
      'extracting verifyToken helper',
      'patched session.ts',
      'patched token.ts',
      'patched middleware.ts',
      'updating 9 call sites',
      'wait, oauth.ts imports old path',
      'fixing broken import',
      'patched oauth.ts',
      'running test suite',
      '3 tests failing, checking',
      'fixed stale mock in auth.test',
      'tests pass 47/47, done',
    ],
  },
];
